//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint_13_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tijdschriften
    {
        public int ISSN { get; set; }
        public string Titel { get; set; }
        public string Auteur { get; set; }
        public string Taal { get; set; }
        public string Afmetingen { get; set; }
        public string gewicht { get; set; }
        public Nullable<System.DateTime> Dag_van_uitgifte { get; set; }
        public string Foto { get; set; }
    }
}
